name: stonesoup_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipywidgets
  - jupyter
  - matplotlib
  - mergedeep
  - more-itertools
  - moviepy
  - notebook
  - numpy =1.24
  - pandas
  - plotly
  - scipy
  - tensorflow =2.18
  - mamba
  # - astropy
  # - confluent_kafka
  # - driven
  # - ffmpeg-python
  # - folium
  # - h5py
  # - object_detection
  # - opencv-python
  # - optree
  # - optuna
  # - ordered-set
  # - ortools
  # - pillow
  # - pymap3d
  # - pytest
  # - python-dateutil
  # - pytube
  # - requests
  # - reverb
  # - rtree
  # - ruamel.yaml
  # - tf_agents
  # - utm
  # - scikit-learn
  # - tensorflow-intel
  # - tensorflow-io-gcs-filesystem
  # - pip:
  #     # - stonesoup
  #     - tqdm
  #     - rich
  #     - requests
  #     - kaleido