name: stonesoup_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - matplotlib
  - numpy>=1.17
  - ordered-set
  - pymap3d
  - ruamel.yaml>=0.16.5
  - rtree
  - scipy
  - utm
  - pandas
  - pillow
  - plotly>=5.0
  - pytest-cov
  - pytest-remotedata
  - pytest-skip-slow
  - sphinx
  - sphinx_rtd_theme>=1.2
  - sphinx-gallery>=0.16
  - ffmpeg-python
  - moviepy
  - opencv-python
  - tensorflow>=2.2.0
  - tensornets
  - astropy
  - ortools
  - pyehm
  - widgetsnbextension
  - jupyterlab
  - pip
  - pip:
      - stonesoup
      - nbclient
      - ipykernel
      - ipywidgets
      - kaleido
      - tqdm
      - rich
      - requests
